# Generated by Django 2.2 on 2021-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("subscription", "0003_auto_20210518_1107")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="stripe_subscription_id",
            field=models.CharField(max_length=400),
        )
    ]
