# Generated by Django 2.2 on 2021-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
    ]
