# Generated by Django 2.2 on 2021-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("subscription", "0007_auto_20210519_0737")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subscription_id",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField()
        ),
    ]
