# Generated by Django 2.2 on 2021-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("subscription", "0010_product_description")]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.RemoveField(model_name="customer", name="stripe_id"),
        migrations.RemoveField(model_name="customer", name="stripe_subscription_id"),
        migrations.RemoveField(model_name="product", name="subscription_id"),
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.Product",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="subscription_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
