# Generated by Django 2.2 on 2021-05-23 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0011_auto_20210521_1438"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(default="", max_length=256)),
                ("subscription_id", models.CharField(default="", max_length=256)),
            ],
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=256)
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.DeleteModel(name="Customer"),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.Product",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
